blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://louismazel.github.io/relizy
    about: Check the official documentation before opening an issue
  - name: ğŸ’¬ Discussions
    url: https://github.com/LouisMazel/relizy/discussions
    about: Ask questions and discuss with the community
  - name: ğŸ“ Code of Conduct
    url: https://github.com/LouisMazel/relizy/blob/main/.github/CODE_OF_CONDUCT.md
    about: Read the code of conduct before opening an issue
