name: Linters

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'apps/**'
      - 'tools/**'
      - pnpm-lock.yaml
      - .github/workflows/linters.yml

jobs:
  linters:
    name: linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js, pnpm and Nx cache
        uses: ./.github/actions/setup

      - name: Run linters
        run: pnpm lint
